moai:
  version: 1.0.0
  update_check_frequency: daily
  version_check:
    enabled: true
    cache_ttl_hours: 24
github:
  enable_trust_5: true
  auto_delete_branches: true
  spec_git_workflow: main_direct
